### ISSUE TITLE
Error when deploying Vert.x Health check

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#202]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/1517/

```
ScannerException: while scanning a quoted scalar
 in 'reader', line 168, column 20:
              image: ' '
                       ^
found unexpected end of stream
 in 'reader', line 218, column 1:
    
    ^

    at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalarSpaces(ScannerImpl.java:1933)
    at org.yaml.snakeyaml.scanner.ScannerImpl.scanFlowScalar(ScannerImpl.java:1847)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchFlowScalar(ScannerImpl.java:1029)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchSingle(ScannerImpl.java:1004)
    at org.yaml.snakeyaml.scanner.ScannerImpl.fetchMoreTokens(ScannerImpl.java:392)
...
(105 additional frame(s) were not displayed)

MarkedYAMLException: while scanning a quoted scalar
 in 'reader', line 168, column 20:
              image: ' '
                       ^
found unexpected end of stream
 in 'reader', line 218, column 1:
    
    ^

 at [Source: java.io.BufferedInputStream@205d7a04; line: 168, column: 19]
    at com.fasterxml.jackson.dataformat.yaml.snakeyaml.error.MarkedYAMLException.from(MarkedYAMLException.java:27)
    at com.fasterxml.jackson.dataformat.yaml.YAMLParser.nextToken(YAMLParser.java:350)
    at com.fasterxml.jackson.core.JsonParser.nextFieldName(JsonParser.java:655)
    at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:219)
    at com.fasterxml.jackson.databind.deser.std.BaseNodeDeserializer.deserializeObject(JsonNodeDeserializer.java:224)
...
(97 additional frame(s) were not displayed)

KubernetesClientException: An error has occurred.
    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:62)
    at io.fabric8.kubernetes.client.KubernetesClientException.launderThrowable(KubernetesClientException.java:53)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:123)
    at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:85)
    at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.load(TemplateOperationsImpl.java:231)
...
(81 additional frame(s) were not displayed)

RuntimeException: Could not create OpenShift pipeline
    at io.fabric8.launcher.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:403)
    at io.fabric8.launcher.service.openshift.impl.fabric8.openshift.client.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:225)
    at sun.reflect.NativeMethodAccessorImpl.invoke0(NativeMethodAccessorImpl.java)
    at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
    at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
...
(75 additional frame(s) were not displayed)

Error while launching project
```

Check the application.yaml,  this looks weird: https://github.com/openshiftio-vertx-boosters/vertx-health-checks-booster/blob/master/.openshiftio/application.yaml#L59

**Comment by gastaldi** [comment]
@quintesse can we enhance the validator in the booster-catalog PR to check if the YAML files structure are parseable?

**Comment by quintesse** [comment]
@gastaldi yes, that certainly seems like something that can be done

**Comment by cescoffier** [comment]
@gastaldi @quintesse I don't write the applicaiton.yaml, the script is generating it for me. So the script needs to be fixed.

**Comment by cescoffier** [comment]
@gastaldi @quintesse  Looking at https://github.com/openshiftio-vertx-boosters/vertx-health-checks-booster-redhat/commit/15a003bf580772cbf7248390d97df48b62f873d2#diff-5dce3a731b5aff7080a31a1adcd60ae7, it comes from the Fabric8 Maven Plugin not generating the name in the descriptor anymore.

**Comment by cescoffier** [comment]
Should be fixed by now.  Waiting for feedback.

**Comment by gastaldi** [comment]
Fixed. Closing
