### ISSUE TITLE
Retry in frontend fails with NPE in `AbstractGitService`

### ISSUE THREAD

**Issue by quintesse** [fabric8-launcher/launcher-backend#26]
Right now if the push fails and you retry you get an NPE in `AbstractGitService`;

```
Caused by: java.lang.NullPointerException
	at io.fabric8.launcher.service.git.impl.AbstractGitService.push(AbstractGitService.java:44)
	at io.fabric8.launcher.core.impl.observers.GitHubStepObserver.pushToGitHubRepository(GitHubStepObserver.java:105)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
...
```

This is because in a retry the last line in the following code in `GitHubStepObserver` returns `null`:

```
    public void pushToGitHubRepository(@Observes @Step(GITHUB_PUSHED) CreateProjectileEvent event) {
        assert event.getGitHubRepository() != null : "Github repository is not set";

        CreateProjectile projectile = event.getProjectile();
        GitHubService gitHubService = gitHubServiceFactory.create(projectile.getGitHubIdentity());
        GitRepository gitHubRepository = event.getGitHubRepository();
```

Using events to pass data from one step to another seems like a bad idea anyway, right?

**Comment by gastaldi** [comment]
Right, we need to restore the state before triggering the events (making a call to getRepository first). It's an easy fix afaik.

I don't see the reason why to blame the event mechanism. Would love to hear any suggestions on how we could improve it.

**Comment by gastaldi** [comment]
I wonder why the assertion failed, a NPE wouldn't happen if that worked
