### ISSUE TITLE
Kubernetes API's Controller class tries to create a project twice, causing Could not create OpenShift pipeline error

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#461]
The /projects endpoint does not return the list of projects immediately once a project is created, therefore making the Controller class think that the project does not exist. 

https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/6149/

```
KubernetesClientException: Failure executing: POST at: https://api.starter-us-east-1.openshift.com/apis/project.openshift.io/v1/projectrequests. Message: projectrequests.project.openshift.io "meuteste2" is forbidden: user rhn-support-ggastald cannot create more than 1 project(s).. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=project.openshift.io, kind=projectrequests, name=meuteste2, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=projectrequests.project.openshift.io "meuteste2" is forbidden: user rhn-support-ggastald cannot create more than 1 project(s)., metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:472)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:411)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
    at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
...
(109 additional frame(s) were not displayed)

RuntimeException: Failed to create ProjectRequest: meuteste2 due Failure executing: POST at: https://api.starter-us-east-1.openshift.com/apis/project.openshift.io/v1/projectrequests. Message: projectrequests.project.openshift.io "meuteste2" is forbidden: user rhn-support-ggastald cannot create more than 1 project(s).. Received status: Status(apiVersion=v1, code=403, details=StatusDetails(causes=[], group=project.openshift.io, kind=projectrequests, name=meuteste2, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=projectrequests.project.openshift.io "meuteste2" is forbidden: user rhn-support-ggastald cannot create more than 1 project(s)., metadata=ListMeta(resourceVersion=null, selfLink=null, additionalProperties={}), reason=Forbidden, status=Failure, additionalProperties={}).
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:374)
...
(103 additional frame(s) were not displayed)

RuntimeException: Could not create OpenShift pipeline
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:424)
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:212)
    at io.fabric8.launcher.service.openshift.api.OpenShiftService$1003093822$Proxy$_$$_WeldClientProxy.configureProject
    at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.applyTemplate(OpenShiftSteps.java:137)
    at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.configureBuildPipeline(OpenShiftSteps.java:67)
...
(94 additional frame(s) were not displayed)

Projectile LauncherCreateProjectile{booster=Booster [id=nodejs_v8-redhat_configmap_booster_production, gitRepo=https://github.com/bucharest-gold/nodejs-configmap-redhat, gitRef=v1.2.2, name=Node.js - HTTP & Config Map, description=Simple HTTP endpoint where the Node.js application uses OpenShift ConfigMap to get the application parameters., contentPath=/tmp/booster-catalog6493528482353254601/.boosters/nodejs_v8-redhat_configmap_booster_production, metadata={app={osio={enabled=false}}}, environments={staging={source={git={ref=v1.2.2}}}, production={source={git={ref=v1.2.2}}}}], openShiftProjectName=meuteste2, gitRepositoryName=meuteste, gitOrganization=null, gitRepositoryDescription=Generated by the Red Hat Developer Launch (https://developers.redhat.com/launch), id=fcdc8702-58d7-4272-9104-b214ab9fb214, startOfStep=0, projectLocation=/tmp/projectDir4826266934426769028} failed to launch. Time Elapsed: 00:00:22.725
```

**Comment by gastaldi** [comment]
Bugzilla created: https://bugzilla.redhat.com/show_bug.cgi?id=1594939
