### ISSUE TITLE
RuntimeException: Could not create OpenShift pipeline

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#558]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/8772/

```
KubernetesClientException: Failure executing: POST at: https://api.starter-ca-central-1.openshift.com/apis/image.openshift.io/v1/namespaces/my-new-app/imagestreamtags. Message: ImageStreamTag.image.openshift.io "my-new-app-database:9.6" is invalid: tag.annotations: Invalid value: "<map>": tag annotations must not be provided or must be equal to the object meta annotations. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=tag.annotations, message=Invalid value: "<map>": tag annotations must not be provided or must be equal to the object meta annotations, reason=FieldValueInvalid, additionalProperties={})], group=image.openshift.io, kind=ImageStreamTag, name=my-new-app-database:9.6, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ImageStreamTag.image.openshift.io "my-new-app-database:9.6" is invalid: tag.annotations: Invalid value: "<map>": tag annotations must not be provided or must be equal to the object meta annotations, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.lambda$configureProject$6(Fabric8OpenShiftServiceImpl.java:344)
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:361)
...
(113 additional frame(s) were not displayed)

RuntimeException: Could not create OpenShift pipeline
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:368)
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:194)
    at io.fabric8.launcher.service.openshift.api.OpenShiftService$1003093822$Proxy$_$$_WeldClientProxy.configureProject
    at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.applyTemplate(OpenShiftSteps.java:137)
    at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.configureBuildPipeline(OpenShiftSteps.java:77)
...
(93 additional frame(s) were not displayed)

Projectile LauncherCreateProjectile{booster=null, openShiftProjectName=my-new-app, gitRepositoryName=addf, gitOrganization=null, gitRepositoryDescription=Generated by the Red Hat Developer Launch (https://developers.redhat.com/launch), id=16081db2-e819-4591-9801-3afa1ddcba11, startOfStep=0, projectLocation=/tmp/projectDir676302747731920133/my-new-app} failed to launch. Time Elapsed: 00:00:08.549
```

This is triggered by the launcher-creator-backend

**Comment by quintesse** [comment]
Closing because dup has more info

**Comment by quintesse** [comment]
Uploading the project in the attached zip file results in the following error:

```
2018-11-01 15:46:16,633 WARNING [LaunchEndpoint] (default task-7) Projectile LauncherCreateProjectile{booster=null, openShiftProjectName=xxxx, gitRepositoryName=xxxx, gitOrganization=null, gitRepositoryDescription=Generated by the Red Hat Developer Launch (https://developers.redhat.com/launch), id=550c7c66-64d1-4505-98b1-6eff89e70696, startOfStep=0, projectLocation=/tmp/projectDir6639663511470481821/xxxx} failed to launch. Time Elapsed: 00:00:07.227: java.lang.RuntimeException: Could not create OpenShift pipeline
	at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:368)
	at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:194)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.bean.proxy.AbstractBeanInstance.invoke(AbstractBeanInstance.java:38)
	at org.jboss.weld.bean.proxy.ProxyMethodHandler.invoke(ProxyMethodHandler.java:100)
	at io.fabric8.launcher.service.openshift.api.OpenShiftService$1003093822$Proxy$_$$_WeldClientProxy.configureProject(Unknown Source)
	at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.applyTemplate(OpenShiftSteps.java:137)
	at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.configureBuildPipeline(OpenShiftSteps.java:77)
	at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:111)
	at io.fabric8.launcher.core.impl.MissionControlImpl.launch(MissionControlImpl.java:39)
	at io.fabric8.launcher.web.endpoints.LaunchEndpoint.doLaunch(LaunchEndpoint.java:147)
	at io.fabric8.launcher.web.endpoints.LaunchEndpoint.uploadZip(LaunchEndpoint.java:126)
	at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldSubclass.uploadZip$$super(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.proxy.TerminalAroundInvokeInvocationContext.proceedInternal(TerminalAroundInvokeInvocationContext.java:49)
	at org.jboss.weld.interceptor.proxy.AroundInvokeInvocationContext.proceed(AroundInvokeInvocationContext.java:77)
	at org.hibernate.validator.internal.cdi.interceptor.ValidationInterceptor.validateMethodInvocation(ValidationInterceptor.java:79)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.weld.interceptor.reader.SimpleInterceptorInvocation$SimpleMethodInvocation.invoke(SimpleInterceptorInvocation.java:73)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeAroundInvoke(InterceptorMethodHandler.java:84)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.executeInterception(InterceptorMethodHandler.java:72)
	at org.jboss.weld.interceptor.proxy.InterceptorMethodHandler.invoke(InterceptorMethodHandler.java:56)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:79)
	at org.jboss.weld.bean.proxy.CombinedInterceptorAndDecoratorStackMethodHandler.invoke(CombinedInterceptorAndDecoratorStackMethodHandler.java:68)
	at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldSubclass.uploadZip(Unknown Source)
	at io.fabric8.launcher.web.endpoints.LaunchEndpoint$Proxy$_$$_WeldClientProxy.uploadZip(Unknown Source)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:498)
	at org.jboss.resteasy.core.MethodInjectorImpl.invoke(MethodInjectorImpl.java:140)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invokeOnTarget(ResourceMethodInvoker.java:295)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:249)
	at org.jboss.resteasy.core.ResourceMethodInvoker.invoke(ResourceMethodInvoker.java:236)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:406)
	at org.jboss.resteasy.core.SynchronousDispatcher.invoke(SynchronousDispatcher.java:213)
	at org.jboss.resteasy.plugins.server.servlet.ServletContainerDispatcher.service(ServletContainerDispatcher.java:228)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:56)
	at org.jboss.resteasy.plugins.server.servlet.HttpServletDispatcher.service(HttpServletDispatcher.java:51)
	at javax.servlet.http.HttpServlet.service(HttpServlet.java:790)
	at io.undertow.servlet.handlers.ServletHandler.handleRequest(ServletHandler.java:85)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:129)
	at io.undertow.websockets.jsr.JsrWebSocketFilter.doFilter(JsrWebSocketFilter.java:130)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.fabric8.launcher.web.providers.CorsFilter.doFilter(CorsFilter.java:49)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.fabric8.launcher.web.providers.gzip.GZipFilter.doFilter(GZipFilter.java:42)
	at io.undertow.servlet.core.ManagedFilter.doFilter(ManagedFilter.java:61)
	at io.undertow.servlet.handlers.FilterHandler$FilterChainImpl.doFilter(FilterHandler.java:131)
	at io.undertow.servlet.handlers.FilterHandler.handleRequest(FilterHandler.java:84)
	at io.undertow.servlet.handlers.security.ServletSecurityRoleHandler.handleRequest(ServletSecurityRoleHandler.java:62)
	at io.undertow.servlet.handlers.ServletDispatchingHandler.handleRequest(ServletDispatchingHandler.java:36)
	at org.wildfly.extension.undertow.security.SecurityContextAssociationHandler.handleRequest(SecurityContextAssociationHandler.java:78)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.swarm.generated.FaviconErrorHandler.handleRequest(FaviconErrorHandler.java:61)
	at io.undertow.server.handlers.PathHandler.handleRequest(PathHandler.java:94)
	at io.undertow.servlet.handlers.security.SSLInformationAssociationHandler.handleRequest(SSLInformationAssociationHandler.java:131)
	at io.undertow.servlet.handlers.security.ServletAuthenticationCallHandler.handleRequest(ServletAuthenticationCallHandler.java:57)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.security.handlers.AbstractConfidentialityHandler.handleRequest(AbstractConfidentialityHandler.java:46)
	at io.undertow.servlet.handlers.security.ServletConfidentialityConstraintHandler.handleRequest(ServletConfidentialityConstraintHandler.java:64)
	at io.undertow.security.handlers.AuthenticationMechanismsHandler.handleRequest(AuthenticationMechanismsHandler.java:60)
	at io.undertow.servlet.handlers.security.CachedAuthenticatedSessionHandler.handleRequest(CachedAuthenticatedSessionHandler.java:77)
	at io.undertow.security.handlers.NotificationReceiverHandler.handleRequest(NotificationReceiverHandler.java:50)
	at io.undertow.security.handlers.AbstractSecurityContextAssociationHandler.handleRequest(AbstractSecurityContextAssociationHandler.java:43)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.security.jacc.JACCContextIdHandler.handleRequest(JACCContextIdHandler.java:61)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at org.wildfly.extension.undertow.deployment.GlobalRequestControllerHandler.handleRequest(GlobalRequestControllerHandler.java:68)
	at io.undertow.server.handlers.PredicateHandler.handleRequest(PredicateHandler.java:43)
	at io.undertow.servlet.handlers.ServletInitialHandler.handleFirstRequest(ServletInitialHandler.java:292)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$100(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:138)
	at io.undertow.servlet.handlers.ServletInitialHandler$2.call(ServletInitialHandler.java:135)
	at io.undertow.servlet.core.ServletRequestContextThreadSetupAction$1.call(ServletRequestContextThreadSetupAction.java:48)
	at io.undertow.servlet.core.ContextClassLoaderSetupAction$1.call(ContextClassLoaderSetupAction.java:43)
	at org.wildfly.extension.undertow.security.SecurityContextThreadSetupAction.lambda$create$0(SecurityContextThreadSetupAction.java:105)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at org.wildfly.extension.undertow.deployment.UndertowDeploymentInfoService$UndertowThreadSetupAction.lambda$create$0(UndertowDeploymentInfoService.java:1508)
	at io.undertow.servlet.handlers.ServletInitialHandler.dispatchRequest(ServletInitialHandler.java:272)
	at io.undertow.servlet.handlers.ServletInitialHandler.access$000(ServletInitialHandler.java:81)
	at io.undertow.servlet.handlers.ServletInitialHandler$1.handleRequest(ServletInitialHandler.java:104)
	at io.undertow.server.Connectors.executeRootHandler(Connectors.java:326)
	at io.undertow.server.HttpServerExchange$1.run(HttpServerExchange.java:812)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
	at java.lang.Thread.run(Thread.java:748)
Caused by: io.fabric8.kubernetes.client.KubernetesClientException: Failure executing: POST at: https://192.168.42.247:8443/apis/image.openshift.io/v1/namespaces/xxxx/imagestreamtags. Message: ImageStreamTag "xxxx-database:9.6" is invalid: tag.annotations: Invalid value: "<map>": tag annotations must not be provided or must be equal to the object meta annotations. Received status: Status(apiVersion=v1, code=422, details=StatusDetails(causes=[StatusCause(field=tag.annotations, message=Invalid value: "<map>": tag annotations must not be provided or must be equal to the object meta annotations, reason=FieldValueInvalid, additionalProperties={})], group=null, kind=ImageStreamTag, name=xxxx-database:9.6, retryAfterSeconds=null, uid=null, additionalProperties={}), kind=Status, message=ImageStreamTag "xxxx-database:9.6" is invalid: tag.annotations: Invalid value: "<map>": tag annotations must not be provided or must be equal to the object meta annotations, metadata=ListMeta(_continue=null, resourceVersion=null, selfLink=null, additionalProperties={}), reason=Invalid, status=Failure, additionalProperties={}).
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.requestFailure(OperationSupport.java:476)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.assertResponseCode(OperationSupport.java:415)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:381)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleResponse(OperationSupport.java:344)
	at io.fabric8.kubernetes.client.dsl.base.OperationSupport.handleCreate(OperationSupport.java:227)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.handleCreate(BaseOperation.java:780)
	at io.fabric8.kubernetes.client.dsl.base.BaseOperation.create(BaseOperation.java:353)
	at io.fabric8.openshift.client.handlers.ImageStreamTagHandler.create(ImageStreamTagHandler.java:45)
	at io.fabric8.openshift.client.handlers.ImageStreamTagHandler.create(ImageStreamTagHandler.java:34)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:133)
	at io.fabric8.kubernetes.client.dsl.internal.NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.createOrReplace(NamespaceVisitFromServerGetWatchDeleteRecreateWaitApplicableImpl.java:57)
	at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.lambda$configureProject$6(Fabric8OpenShiftServiceImpl.java:344)
	at java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:193)
	at java.util.ArrayList$ArrayListSpliterator.forEachRemaining(ArrayList.java:1382)
	at java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:481)
	at java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:471)
	at java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:418)
	at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:361)
	... 98 more
```

The same resources apply without any problem using `oc apply .openshiftio/application.yaml`

[xxxx.zip](https://github.com/fabric8-launcher/launcher-backend/files/2539143/xxxx.zip)

**Comment by quintesse** [comment]
Ok, I just copied the info from the newer dup to this one. Re-opening ;-)

**Comment by quintesse** [comment]
We have to investigate if this is due to a limitation in the API the backend uses to communicate with OpenShift or that there's actually something wrong with the template (which is generated by `oc new-app` btw!). Perhaps the OpenShift API is more forgiving than the K8s API in some cases?

**Comment by quintesse** [comment]
Btw, tested the zip with the Launcher Backend's `/upload` endpoint using the Swagger page. Only filled in the required fields projectName and repository, both set to "xxxx".

It can also be reproduced from the Creator's swagger page using the `/launch` endpoint. In that case I used:

```
```

**Comment by quintesse** [comment]
Btw2: it's only reproducible with an app that contains the `database` capability, if you use an app that only has the `rest` capability the error won't show up. So it must be something specific to the resources that created for the Database app.

**Comment by gastaldi** [comment]
There are two solutions:

1. Remove the "annotations" from the ImageStreamTag
      ```annotations:
        openshift.io/generated-by: OpenShiftNewApp
        openshift.io/imported-from: 172.30.1.1:5000/openshift/postgresql:9.6```
2. or add the same set of annotations to the `tag:` inside the ImageStreamTag element

Why the `oc` command ignores that? It's a mystery because the Fabric8 Openshift client performs a POST with the same content as in the template and this error comes from the server

**Comment by gastaldi** [comment]
We opted to remove the annotations, as they do not make sense in our context
