### ISSUE TITLE
RuntimeException: Could not create OpenShift pipeline

### ISSUE THREAD

**Issue by gastaldi** [fabric8-launcher/launcher-backend#698]
https://errortracking.prod-preview.openshift.io/openshift_io/fabric8-launcher-backend/issues/10528/

```
JsonMappingException: No resource type found for:v1#List
 at [Source: (BufferedInputStream); line: 72, column: 22]
    at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:270)
    at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1711)
    at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
    at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
    at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
...
(116 additional frame(s) were not displayed)

KubernetesClientException: An error has occurred.
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:353)
...
(112 additional frame(s) were not displayed)

RuntimeException: Could not create OpenShift pipeline
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:392)
    at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:213)
    at io.fabric8.launcher.service.openshift.api.OpenShiftService$1403678796$Proxy$_$$_WeldClientProxy.configureProject
    at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.applyTemplate(OpenShiftSteps.java:144)
    at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.configureBuildPipeline(OpenShiftSteps.java:79)
...
(106 additional frame(s) were not displayed)

Projectile LauncherCreateProjectile{id=43c613f1-34b6-4b04-89bb-0333688ef1be, startOfStep=0, projectLocation=/tmp/projectDir8844046231608737924, booster=Booster [id=vert.x_redhat_cache_booster_staging, gitRepo=https://github.com/openshiftio-vertx-boosters/vertx-cache-booster-redhat, gitRef=v9, name=Eclipse Vert.x - Cache, description=Demonstrate how to use a cache server in Eclipse Vert.x, contentPath=/tmp/booster-catalog4760524521678225171/.boosters/vert.x_redhat_cache_booster_staging, metadata={app={launcher={runsOn=[!starter]}, osio={enabled=false}}}, environments={staging={source={git={ref=v9}}}, production={source={git={ref=v9}}}}], openShiftProjectName=lucid-can, gitRepositoryName=lucid-can, gitOrganization=null, gitRepositoryDescription=Generated by the Red Hat Developer Launcher (https://developers.redhat.com/launch)} failed to launch. Time Elapsed: 00:00:07.684
```

**Comment by gastaldi** [comment]
Full stacktrace: 

```
com.fasterxml.jackson.databind.JsonMappingException: No resource type found for:v1#List
 at [Source: (BufferedInputStream); line: 72, column: 22]
	at com.fasterxml.jackson.databind.JsonMappingException.from(JsonMappingException.java:271)
	at com.fasterxml.jackson.databind.DeserializationContext.mappingException(DeserializationContext.java:1718)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:78)
	at io.fabric8.kubernetes.internal.KubernetesDeserializer.deserialize(KubernetesDeserializer.java:32)
	at com.fasterxml.jackson.databind.ObjectReader._bindAndClose(ObjectReader.java:1611)
	at com.fasterxml.jackson.databind.ObjectReader.readValue(ObjectReader.java:1188)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:130)
	at io.fabric8.kubernetes.client.utils.Serialization.unmarshal(Serialization.java:93)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.load(TemplateOperationsImpl.java:238)
	at io.fabric8.openshift.client.dsl.internal.TemplateOperationsImpl.load(TemplateOperationsImpl.java:61)
	at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:353)
	at io.fabric8.launcher.service.openshift.impl.Fabric8OpenShiftServiceImpl.configureProject(Fabric8OpenShiftServiceImpl.java:213)
	at io.fabric8.launcher.core.impl.steps.OpenShiftSteps.applyTemplate(OpenShiftSteps.java:147)
```
